### ISSUE TITLE
Do we need django-gardian ?

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/platon#2]
https://pypi.org/project/django-guardian/

**Comment by JUILLARD-Thomas** [comment]
We don't need django-gardian. Django API provide Customizing authentication with Group, User and Custom permissions.
[https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#handling-object-permissions](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#handling-object-permissions)
